### ISSUE TITLE
Can not go back to first page

### ISSUE THREAD

**Issue by quantrung9** [timble/jekyll-pagination#3]
Hi,

I added your pagination template to index.html, but when I try to click on page 1 to go back to the first page, it can not navigate.

**Comment by quantrung9** [comment]
Sorry, I forgot to replace {{ page.paginate_root }} on line 51 and 60 to `{{ "/" | prepend: site.baseurl }}`, as you mentioned on https://github.com/timble/jekyll-pagination/commit/16fde5fe1c0300851b9ae0abfc8a39787a7da051

**Comment by quantrung9** [comment]
I've made a pull request https://github.com/timble/jekyll-pagination/pull/4 to fix this issue

**Comment by robinpoort** [comment]
@iamquan Thank you for creating the PR!

However this is not needed since the root of the blog can be set on the blog index page. We've released a new version and updated the README to show how this can be done.
